---
title: "5HT data Summary"
author: "SawchukS"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      eval = TRUE,
                      out.width = "100%",
                      warning = FALSE,
                      cache = TRUE)

library(metap)
library(feather)
library(Seurat)
library(ggplot2)

MD = projHCT::sheets$MD
cMD = projHCT::sheets$cleanMD

HTRgenesINT = c(
  "HTR1A", "HTR1B", "HTR1D", "HTR1E", "HTR1F", "HTR2A", "HTR2B", "HTR2C", "HTR4", "HTR5A", "HTR6", "HTR7"
)
HTRgenes12 = c("HTR1A", "HTR1B", "HTR1D", "HTR1E", "HTR1F", "HTR2A", "HTR2B", "HTR2C")
HTR1 = c("HTR1A", "HTR1B", "HTR1D", "HTR1E", "HTR1F")
HTR2 = c("HTR2A", "HTR2B", "HTR2C")
HTR0 = c("HTR4", "HTR5A", "HTR6", "HTR7")

legend_guides = c(size = guide_legend(title = "% Exp"), color = guide_colorbar(title = "Avg Exp"))
```

# No filter summary

```{r}
MD = projHCT::sheets$MD
MD$Cortical_area = gsub("MTG", "TCx", MD$Cortical_area)
cells = list.files("~/proj/proj5HT/den/serotonin/output/")
cell_json = list.files("~/proj/proj5HT/den/serotonin/output/", recursive = TRUE, full.names = TRUE, pattern = ".json")
merged_metadata = read.csv("~/proj/proj5HT/den/serotonin/Data/merged_metadata.csv", row.names = NULL, check.names = FALSE)[, -1]
output_cellsMD = MD[MD$cell_name %in% cells,]
```

```{r}
ggplot(output_cellsMD, aes(x = Species, fill = Species)) +
  geom_bar() +
  theme_minimal()

ggplot(output_cellsMD, aes(x = subclass_Corr, fill = subclass_Corr)) +
  geom_bar() +
  facet_wrap(~Species, nrow = 3) +
  theme_minimal()
```

```{r}
ggplot(output_cellsMD, aes(x = subclass_Corr, fill = subclass_Corr)) +
  geom_bar() +
  facet_wrap(~Species, nrow = 2) +
  theme_minimal()
```

```{r}
# Predicted subclass
ggplot(output_cellsMD, aes(x = predicted_subclass, fill = predicted_subclass)) +
  geom_bar() +
  facet_wrap(~Species, nrow = 2) +
  theme_minimal()
```

# Cells with 50s puff protocols #

```{r}
msmry = projHCT::sheets$dfs$massSmry
puffPro = msmry[grep("50spuff", msmry$stimulus_description),]
puffCells = unique(puffPro$cell_name)
puffCellsMD = MD[MD$cell_name %in% unique(puffPro$cell_name),]
```

```{r}

ggplot(puffCellsMD, aes(x = Species, fill = Species)) +
  geom_bar() +
  theme_minimal()

ggplot(puffCellsMD, aes(x = subclass_Corr, fill = subclass_Corr)) +
  geom_bar() +
  facet_wrap(~Species, nrow = 4) +
  theme_minimal()

```

```{r}
ggplot(puffCellsMD, aes(x = subclass_Corr, fill = subclass_Corr)) +
  geom_bar() +
  facet_wrap(~Species, nrow = 2) +
  theme_minimal()
```

```{r}
ggplot(puffCellsMD, aes(x = subclass_Corr, fill = Cortical_area)) +
  geom_bar(position = "dodge") +
  facet_wrap(~Species, nrow = 2) +
  theme_minimal()

ggplot(output_cellsMD, aes(x = subclass_Corr, fill = Cortical_area)) +
  geom_bar(position = "dodge") +
  facet_wrap(~Species, nrow = 2) +
  theme_minimal()


```

```{r}
ggplot(puffCellsMD, aes(x = predicted_subclass, fill = Cortical_area)) +
  geom_bar(position = "dodge") +
  facet_wrap(~Species, nrow = 2) +
  theme_minimal()

ggplot(output_cellsMD, aes(x = predicted_subclass, fill = Cortical_area)) +
  geom_bar(position = "dodge") +
  facet_wrap(~Species, nrow = 2) +
  theme_minimal()


```

```{r}
ggplot(puffCellsMD, aes(x = subclass_Corr, fill = Cortical_area)) +
  geom_bar(position = "dodge") +
  facet_wrap(~Species, nrow = 2) +
  theme_minimal()

ggplot(output_cellsMD, aes(x = subclass_Corr, fill = Cortical_area)) +
  geom_bar(position = "dodge") +
  facet_wrap(~Species, nrow = 2) +
  theme_minimal()


```

# Filter out and build basic figures for each

```{r}
output_cellsMD = output_cellsMD %>% 
  dplyr::filter(Species %in% c("Human", "M.nemestrina")) %>% 
  dplyr::filter(class_Corr %in% c("exc", "Glutamatergic")) %>% 
  dplyr::filter(Cortical_area %in% c("MCx", "TCx"))

puffCellsMD = puffCellsMD %>% 
  dplyr::filter(Species %in% c("Human", "M.nemestrina")) %>% 
  dplyr::filter(class_Corr %in% c("exc", "Glutamatergic")) %>% # %>% 
  dplyr::filter(Cortical_area %in% c("MCx", "TCx"))# %>% 
```

```{r}
ggplot(puffCellsMD, aes(x = subclass_Corr, fill = Cortical_area)) +
  geom_bar() +
  #geom_bar(position = "dodge") +
  facet_wrap(~Species, nrow = 2) +
  theme_minimal()

ggplot(output_cellsMD, aes(x = subclass_Corr, fill = Cortical_area)) +
  geom_bar() +
  #geom_bar(position = "dodge") +
  facet_wrap(~Species, nrow = 2) +
  theme_minimal()
```


```{r}

need_analysis = puffCellsMD[!puffCellsMD$cell_name %in% output_cellsMD$cell_name,]

write.csv(need_analysis, "~/proj/proj5HT/den/serotonin/Data/50sPuffProtocols_to_add_to_analysis.csv")

ggplot(need_analysis, aes(x = subclass_Corr, fill = Cortical_area)) +
  geom_bar() +
  #geom_bar(position = "dodge") +
  facet_wrap(~Species, nrow = 2) +
  theme_minimal()

```

```{r}
grid.arrange(
ggplot(puffCellsMD, aes(x = subclass_Corr, fill = Cortical_area)) +
  geom_bar() +
  #geom_bar(position = "dodge") +
  facet_wrap(~Species, nrow = 2) +
  ggtitle("Cells with 50spuff protocols") +
  theme_minimal() +
  theme(legend.position = "none"),

ggplot(output_cellsMD, aes(x = subclass_Corr, fill = Cortical_area)) +
  geom_bar() +
  ggtitle("Cells already analyzed") +
  facet_wrap(~Species, nrow = 2) +
  theme_minimal() +
  theme(legend.position = "none"),

ggplot(need_analysis, aes(x = subclass_Corr, fill = Cortical_area)) +
  geom_bar() +
  ggtitle("Cells for analysis") +
  facet_wrap(~Species, nrow = 2) +
  theme_minimal() +
  theme(
    legend.position = "inside",
    legend.position.inside = c(0.7,0.9)),
ncol = 3
)

```




# Already analyzed cell compile 

```{r}
my_list = jsonlite::fromJSON(cell_json[3])
plot(x = my_list$spike_puff0$spike_times, y = my_list$spike_puff0$Instantaneous_frequency)
```

```{r}

cell_json[3]

jfile = cell_json[grep(i, cell_json)]
jlist = jsonlite::fromJSON(jfile)
```

