---
title: "Seurat figures for off-pipeline data"
author: "SawchukS"
date: "2025-07-16"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      eval = TRUE,
                      out.width = "100%",
                      warning = FALSE,
                      cache = TRUE)

library(metap)
library(feather)
library(Seurat)
library(ggplot2)

MD = projHCT::sheets$MD
cMD = projHCT::sheets$cleanMD

HTRgenesINT = c(
  "HTR1A", "HTR1B", "HTR1D", "HTR1E", "HTR1F", "HTR2A", "HTR2B", "HTR2C", "HTR4", "HTR5A", "HTR6", "HTR7"
)
HTRgenes12 = c("HTR1A", "HTR1B", "HTR1D", "HTR1E", "HTR1F", "HTR2A", "HTR2B", "HTR2C")
HTR1 = c("HTR1A", "HTR1B", "HTR1D", "HTR1E", "HTR1F")
HTR2 = c("HTR2A", "HTR2B", "HTR2C")
HTR0 = c("HTR4", "HTR5A", "HTR6", "HTR7")

legend_guides = c(size = guide_legend(title = "% Exp"), color = guide_colorbar(title = "Avg Exp"))

range_colour = scale_colour_gradientn(colours = c("lightgrey", "blue"), limits = c(0, 10),         # min / max shown
    oob = scales::squish        # squish out-of-range values to limits
  )

# brain = readRDS("~/proj5HT/data-raw/Seurat/offPipeline-Macaque_PatchSeq_excitatory.rds")
#cMTG = readRDS("~/proj5HT/data-raw/Seurat/MacaqueMTG_10xFACs.rds")

inhB = readRDS("~/proj5HT/data-raw/Seurat/offPipeline-Macaque_PatchSeq_inhibitory.rds")

unique(inhB$subclass_Corr)
table(inhB$subclass_Corr)


brain = subset(brain, subset = Cortical_area %in% c("TCx", "MCx"))
#brain = subset(brain, subset = Cortical_area %in% c("TCx"))
brain46 = subset(brain, subset = subclass_Corr %in% c("L4_IT", "L6_IT", "L5/6_NP", "L6b", "L6_CT"))
brain = subset(brain, subset = subclass_Corr %in% c("L2/3_IT", "L5_IT", "L5_ET"))

cMTG$subclass = as.character(gsub(" ", "_", cMTG$subclass_label))

cMTG64 = subset(cMTG, subset = subclass_label %in% c("L2/3 IT", "L5 IT", "L5 ET"))
cMTG = subset(cMTG, subset = subclass_label %in% c("L2/3 IT", "L5 IT", "L5 ET"))


#inhb = subset(brain, subset = neighborhood_Corr_label %in% c("it_types", "l5et_l56np_l6ct_l6b"))

unique(brain$neighborhood_Corr_label)
pValbChand = subset(brain, subset = subclass %in% c("Chandelier", "Pvalb"))

```

## Figures
Combined shows nCount_RNA being far from each other
```{r, eval = TRUE}
VlnPlot(brain, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), group.by = "set", ncol = 3)
```

## Violin plots Without Normalizing the data
```{r, fig.height=15, fig.width=12}
VlnPlot(brain, features = HTRgenesINT, pt.size = 0.2, ncol = 4, group.by = "subclass_Corr", same.y.lims = TRUE)
```

```{r, fig.height=4, fig.width=10}
VlnPlot(brain, features = HTR1, pt.size = 0.2, ncol = 5, group.by = "subclass_Corr",layer = "counts", same.y.lims = TRUE)
```

```{r, fig.height=4, fig.width=6}
VlnPlot(brain, features = HTR2, pt.size = 0.2, ncol = 3, group.by = "subclass_Corr", layer = "counts", same.y.lims = TRUE)
```

```{r, fig.height=4, fig.width=8}
VlnPlot(brain, features = HTR0, pt.size = 0.2, ncol = 4, group.by = "subclass_Corr", layer = "counts", same.y.lims = TRUE)
```

## Dotplots
```{r, fig.height=4, fig.width=8, eval =TRUE}
DotPlot(object = brain, features = HTRgenesINT, group.by = "subclass_Corr", scale = FALSE) + guides(legend_guides) + ggtitle("Smart-Seq Patch-Seq")

DotPlot(object = subset(brain, subset = Cortical_area %in% c("TCx", "MCx")), features = HTRgenesINT, group.by = "subclass_Corr", split.by = "Cortical_area", scale = FALSE) + guides(legend_guides)

unique(brain$Cortical_area)

```

```{r, fig.height=8, fig.width=10, eval =FALSE}
DotPlot(object = brain, features = HTR1, group.by = "subclass_Corr", scale = FALSE) + guides(legend_guides)
```

```{r, fig.height=8, fig.width=6, eval =FALSE}
DotPlot(object = brain, features = HTR2, group.by = "subclass_Corr", scale = FALSE) + guides(legend_guides)
```

```{r, fig.height=8, fig.width=8, eval =FALSE}
DotPlot(object = brain, features = HTR0, group.by = "subclass_Corr", scale = FALSE) + guides(legend_guides)
```

## Plot Cluster types 

### L2/3 IT cluster types

```{r}
VlnPlot(object = subset(brain, subset = subclass_Corr %in% "L2/3_IT"), features = HTRgenesINT, group.by = "cluster.x")
VlnPlot(object = subset(brain, subset = subclass_Corr %in% "L2/3_IT"), features = HTR1, group.by = "cluster_Corr", ncol = 5)
VlnPlot(object = inhB, features = HTR1, group.by = "subclass_Corr", ncol = 5)
```

```{r}

dp_format = guides(legend_guides) + range_colour + scale_size(limits = c(0, 100))

grid.arrange(
DotPlot(object = subset(brain, subset = subclass_Corr %in% "L2/3_IT"), features = HTRgenesINT, group.by = "cluster_Corr", scale = FALSE) + guides(legend_guides) + range_colour + scale_size(limits = c(0, 100)) + ggtitle("L2/3 Cluster ID Smart-Seq Patch-Seq"),
DotPlot(object = subset(cMTG, subset = subclass_label %in% "L2/3 IT"), features = HTRgenesINT, group.by = "cluster", scale = FALSE) + guides(legend_guides) + range_colour + scale_size(limits = c(0, 100)) + ggtitle("L2/3 Cluster ID for 10x-FACs data"),
nrow = 2
)

grid.arrange(
DotPlot(object = subset(brain, subset = subclass_Corr %in% "L5_IT"), features = HTRgenesINT, group.by = "cluster_Corr", scale = FALSE) + guides(legend_guides) + range_colour + scale_size(limits = c(0, 100)) + ggtitle("L5_IT Cluster ID Smart-Seq Patch-Seq"),
DotPlot(object = subset(cMTG, subset = subclass_label %in% "L5 IT"), features = HTRgenesINT, group.by = "cluster", scale = FALSE) + guides(legend_guides) + range_colour + scale_size(limits = c(0, 100)) + ggtitle("L5_IT Cluster ID for 10x-FACs data"),
nrow = 2
)

grid.arrange(
DotPlot(object = subset(brain, subset = subclass_Corr %in% "L5_ET"), features = HTRgenesINT, group.by = "cluster_Corr", scale = FALSE) + guides(legend_guides) + range_colour + scale_size(limits = c(0, 100)) + ggtitle("L5 ET Cluster ID Smart-Seq Patch-Seq"),
DotPlot(object = subset(cMTG, subset = subclass_label %in% "L5 ET"), features = HTRgenesINT, group.by = "cluster", scale = FALSE) + guides(legend_guides) + range_colour + scale_size(limits = c(0, 100)) + ggtitle("L5 ET Cluster ID fo 10x-FACs data"),
nrow = 2
)
```

```{r}



```

### L5 ET cluster types

```{r}
VlnPlot(object = subset(brain, subset = subclass_Corr %in% "L5_ET"), features = HTRgenesINT, group.by = "cluster_Corr_label")
```

```{r}
DotPlot(object = subset(brain, subset = subclass_Corr %in% "L5_ET"), features = HTRgenesINT, group.by = "cluster_Corr_label", scale = FALSE) + guides(legend_guides)

unique(brain$Species)

DotPlot(object = subset(brain, subset = subclass_Corr %in% "L5_ET"), features = HTRgenesINT, group.by = "cluster_Corr_label", scale = FALSE)


DotPlot(object = subset(brain, subset = subclass_Corr %in% "L5_ET"), features = HTRgenesINT, group.by = "Species", split.by = "cluster_Corr_label", scale = FALSE)
DotPlot(object = subset(brain, subset = subclass_Corr %in% "L5_ET"), features = HTRgenesINT, group.by = "Species", scale = FALSE) + guides(legend_guides) + ggtitle("L5 ET HTR subtype expression between macaque species")


DotPlot(object = subset(brain, subset = subclass_Corr == "L5_ET"), features = HTRgenesINT, group.by = "Species", split.by = "cluster_Corr_label", scale = FALSE)


obj <- subset(brain, subset = subclass_Corr == "L5_ET")
obj$Species <- factor(obj$Species)
obj$Species <- droplevels(obj$Species)

plots <- lapply(levels(obj$Species), function(sp) {
  DotPlot(
    object = subset(obj, subset = Species == sp),
    features = HTR2,
    group.by = "cluster_Corr",
    scale = FALSE
  ) + ggtitle(sp) +
    theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
    + guides(legend_guides)
})

wrap_plots(plots, ncol = 1)

library(patchwork)


```

```{r}

grid.arrange(
DotPlot(object = subset(cMTG, subset = subclass_label %in% "L5 ET"), features = HTRgenesINT, group.by = "cluster", scale = FALSE) + guides(legend_guides) + ggtitle("L5 ET Cluster ID fo 10x-FACs data"),
DotPlot(object = subset(brain, subset = subclass %in% "L5 ET"), features = HTRgenesINT, group.by = "cluster", scale = FALSE) + guides(legend_guides) + ggtitle("L5 ET Cluster ID Smart-Seq Patch-Seq"),
nrow = 2
)
```


# ClusterMD cells

```{r}
cluster_MD = read.csv("data-raw/hct_cluster_matched.csv")[,-1]

cluster_cells = as.character(dPatch$cell_name[cluster_MD$cell_name %in% dPatch$cell_name])

#cluster_cells %in% brain$cell_name

#obj = subset(dPatch, subset = cell_name %in% cluster_cells)
obj = subset(dPatch, subset = subclass_Corr %in% c("L2/3_IT", "L5_IT", "L5_ET", "L6_IT"))

obj = subset(obj, subset = Genes.Detected >= 2000 &
               percent_reads_aligned_to_introns >= 15 &
               marker_sum_norm_label >=0.3 & 
               quality_score_label >= 0.25 & 
               score.Corr_label >= 0.4)


obj$assigned_depth = ifelse(is.na(obj$LIMS_depth), obj$Depth_from_pia*.77, obj$LIMS_depth)
obj <- subset(obj, subset = !is.na(assigned_depth))


df <- FetchData(
  obj,
  vars = c("LIMS_depth", "subclass_Corr", "cell_name", "Depth_from_pia", "assigned_depth", "Cortical_area", HTRgenes12)
)

df_long <- df %>%
  tidyr::pivot_longer(
    cols = all_of(HTRgenes12),
    names_to = "gene",
    values_to = "expression"
  )


ggplot(df_long, aes(x = assigned_depth, y = expression)) +
  geom_point(alpha = 0.3, size = 0.4) +
  geom_smooth(method = "loess", se = FALSE) +
  facet_grid(subclass_Corr ~ gene) +  # rows = subclass, cols = gene
  theme_bw() +
  labs(
    x = "LIMS depth",
    y = "HTR expression",
    title = "HTR gene expression vs depth by subclass_Corr"
  )


```



