---
title: "Seurat figures for off-pipeline data"
author: "SawchukS"
date: "2025-07-16"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      eval = TRUE,
                      out.width = "100%",
                      warning = FALSE,
                      cache = TRUE)

library(metap)
library(feather)
library(Seurat)
library(ggplot2)

MD = projHCT::sheets$MD
cMD = projHCT::sheets$cleanMD

HTRgenesINT = c(
  "HTR1A", "HTR1B", "HTR1D", "HTR1E", "HTR1F", "HTR2A", "HTR2B", "HTR2C", "HTR4", "HTR5A", "HTR6", "HTR7"
)
HTRgenes12 = c("HTR1A", "HTR1B", "HTR1D", "HTR1E", "HTR1F", "HTR2A", "HTR2B", "HTR2C")
HTR1 = c("HTR1A", "HTR1B", "HTR1D", "HTR1E", "HTR1F")
HTR2 = c("HTR2A", "HTR2B", "HTR2C")
HTR0 = c("HTR4", "HTR5A", "HTR6", "HTR7")

legend_guides = c(size = guide_legend(title = "% Exp"), color = guide_colorbar(title = "Avg Exp"))

hMTG = readRDS("~/proj/proj5HT/data-raw/Seurat/HumanMTG_10xFACs.rds")
cMTG = readRDS("~/proj/proj5HT/data-raw/Seurat/ChimpMTG_10xFACs.rds")
mMTG = readRDS("~/proj/proj5HT/data-raw/Seurat/MacaqueMTG_10xFACs.rds")
gMTG = readRDS("~/proj/proj5HT/data-raw/Seurat/GorillaMTG_10xFACs.rds")

# Used aMTG for the metadata. Need to be considerate of naming of variables
#cMTG$subclass = cMTG$subclass_label
mMTG = subset(mMTG, subset = subclass_label %in% c('L5 IT','L5 ET',"L2/3 IT"))
```

# Setup capacity to compare with human data.

```{r include=FALSE}
#cMTG = subset(cMTG, subset = neighbourhoodCorr %in% c("it_types", "l5et_l56np_l6ct_l6b"))


```

## Figures
Combined shows nCount_RNA being far from each other

## Violin plots Without Normalizing the data
```{r, fig.height=15, fig.width=12}
VlnPlot(mMTG, features = HTRgenesINT, pt.size = 0.2, ncol = 4, group.by = "subclass_label", same.y.lims = TRUE)
VlnPlot(gMTG, features = HTRgenesINT, pt.size = 0.2, ncol = 4, group.by = "subclass_label", same.y.lims = TRUE)
VlnPlot(cMTG, features = HTRgenesINT, pt.size = 0.2, ncol = 4, group.by = "subclass_label", same.y.lims = TRUE)
VlnPlot(hMTG, features = HTRgenesINT, pt.size = 0.2, ncol = 4, group.by = "subclass_label", same.y.lims = TRUE)
```

# 5HT2

### Human vs Macaque vs Chimp vs Gorilla

```{r fig.dims = c(4,4)}
grid.arrange(
  DotPlot(
    object = hMTG,
    features = HTR2,
    group.by = "subclass_label",
    scale = FALSE,
        scale.min = 0,
    scale.max = 100,
    cols = c("white", "blue")
  ) + guides(legend_guides) + ggtitle("Human TCx 10xFACs"),
  DotPlot(
    object = mMTG,
    features = HTR2,
    group.by = "subclass_label",
    scale = FALSE,
        scale.min = 0,
    scale.max = 100,
    cols = c("white", "blue")
    ) + guides(legend_guides) + ggtitle("Macaque TCx 10xFACs"),
  DotPlot(
    object = cMTG,
    features = HTR2,
    group.by = "subclass_label",
    scale = FALSE,
        scale.min = 0,
    scale.max = 100,
    cols = c("white", "blue")
  ) + guides(legend_guides) + ggtitle("Chimp TCx 10xFACs"),
  DotPlot(
    object = gMTG,
    features = HTR2,
    group.by = "subclass_label",
    scale = FALSE,
        scale.min = 0,
    scale.max = 100,
    cols = c("white", "blue")
  ) + guides(legend_guides) + ggtitle("Gorilla TCx 10xFACs"),
  ncol = 4
)

```

# HTR1

### Macaque, Chimp, Gorilla, and Human comparison of HTR1 genes 

```{r fig.dims = c(4,4)}
grid.arrange(
  DotPlot(
    object = hMTG,
    features = HTR1,
    group.by = "subclass_label",
    scale = FALSE,
    scale.min = 0,
    scale.max = 100,
    cols = c("white", "blue")
  ) + guides(legend_guides) + ggtitle("Human TCx 10xFACs"),
  DotPlot(
    object = mMTG,
    features = HTR1,
    group.by = "subclass_label",
    scale = FALSE,
    scale.min = 0,
    scale.max = 100,
    cols = c("white", "blue")
    ) + guides(legend_guides) + ggtitle("Macaque TCx 10xFACs"),
  DotPlot(
    object = cMTG,
    features = HTR1,
    group.by = "subclass_label",
    scale = FALSE,
    scale.min = 0,
    scale.max = 100,
    cols = c("white", "blue")
  ) + guides(legend_guides) + ggtitle("Chimp TCx 10xFACs"),
  DotPlot(
    object = gMTG,
    features = HTR1,
    group.by = "subclass_label",
    scale = FALSE,
    scale.min = 0,
    scale.max = 100,
    cols = c("white", "blue")
  ) + guides(legend_guides) + ggtitle("Gorilla TCx 10xFACs"),
  ncol = 4
)

```


```{r fig.dims = c(4,4)}
grid.arrange(
  DotPlot(
    object = hMTG,
    features = HTR0,
    group.by = "subclass_label",
    scale = FALSE,
    scale.min = 0,
    scale.max = 100,
    cols = c("white", "blue")
  ) + guides(legend_guides) + ggtitle("Human TCx 10xFACs"),
  DotPlot(
    object = mMTG,
    features = HTR0,
    group.by = "subclass_label",
    scale = FALSE,
    scale.min = 0,
    scale.max = 100,
    cols = c("white", "blue")
    ) + guides(legend_guides) + ggtitle("Macaque TCx 10xFACs"),
  DotPlot(
    object = cMTG,
    features = HTR0,
    group.by = "subclass_label",
    scale = FALSE,
    scale.min = 0,
    scale.max = 100,
    cols = c("white", "blue")
  ) + guides(legend_guides) + ggtitle("Chimp TCx 10xFACs"),
  DotPlot(
    object = gMTG,
    features = HTR0,
    group.by = "subclass_label",
    scale = FALSE,
    scale.min = 0,
    scale.max = 100,
    cols = c("white", "blue")
  ) + guides(legend_guides) + ggtitle("Gorilla TCx 10xFACs"),
  ncol = 4
)

```



```{r}
grid.arrange(
  DotPlot(
    object = hMTG,
    features = HTR2,
    group.by = "subclass_label",
    scale = FALSE,
    cols = c("white", "blue")
  ) + guides(legend_guides) + ggtitle("Human TCx 10x"),
  DotPlot(
    object = macMTG,
    features = HTR2,
    group.by = "subclass_label",
    scale = FALSE,
    cols = c("white", "blue")
  ) + guides(legend_guides) + ggtitle("Macaque TCx 10x"),
  DotPlot(
    object = cMTG,
    features = HTR2,
    group.by = "subclass_label",
    scale = FALSE,
    cols = c("white", "blue")
  ) + guides(legend_guides) + ggtitle("Chimp TCx 10x"),
  ncol = 3
)
```


## Plot Cluster types 

### L2/3 IT cluster types

```{r}
VlnPlot(object = subset(brain, subset = subclass %in% "L2/3 IT"), features = HTRgenesINT, group.by = "cluster")
```

```{r}

grid.arrange(
DotPlot(object = subset(brain, subset = subclass %in% "L2/3 IT"), features = HTRgenesINT, group.by = "cluster", scale = FALSE) + guides(legend_guides) + ggtitle("L2/3 Cluster ID Smart-Seq Patch-Seq"),
DotPlot(object = subset(cMTG, subset = subclass_label %in% "L2/3 IT"), features = HTRgenesINT, group.by = "cluster", scale = FALSE) + guides(legend_guides) + ggtitle("L2/3 Cluster ID fo 10x-FACs data"),
nrow = 2
)
```

```{r}

brain2 = subset(brain, subset = Cortical_area %in% "TCx")

grid.arrange(
DotPlot(object = subset(brain2, subset = subclass %in% "L5 ET"), features = HTRgenesINT, group.by = "cluster", scale = FALSE) + guides(legend_guides) + ggtitle("L5 ET Cluster ID Smart-Seq Patch-Seq"),
DotPlot(object = subset(brain2, subset = subclass %in% "L2/3 IT"), features = HTRgenesINT, group.by = "cluster", scale = FALSE) + guides(legend_guides) + ggtitle("L2/3 Cluster ID Smart-Seq Patch-Seq"),
#DotPlot(object = subset(cMTG, subset = subclass_label %in% "L5 ET"), features = HTRgenesINT, group.by = "cluster", scale = FALSE) + guides(legend_guides) + ggtitle("L5 ET Cluster ID fo 10x-FACs data"),
#DotPlot(object = subset(cMTG, subset = subclass_label %in% "L2/3 IT"), features = HTRgenesINT, group.by = "cluster", scale = FALSE) + guides(legend_guides) + ggtitle("L2/3 Cluster ID fo 10x-FACs data"),
nrow = 2
)
```

### L5 ET cluster types

```{r}
VlnPlot(object = subset(brain, subset = subclass %in% "L5 ET"), features = HTRgenesINT, group.by = "cluster")
```

```{r}
DotPlot(object = subset(brain, subset = subclass %in% "L5 ET"), features = HTRgenesINT, group.by = "cluster", scale = FALSE) + guides(legend_guides)
```

```{r}

grid.arrange(
DotPlot(object = subset(cMTG, subset = subclass_label %in% "L5 ET"), features = HTRgenesINT, group.by = "cluster", scale = FALSE) + guides(legend_guides) + ggtitle("L5 ET Cluster ID fo 10x-FACs data"),
DotPlot(object = subset(brain, subset = subclass %in% "L5 ET"), features = HTRgenesINT, group.by = "cluster", scale = FALSE) + guides(legend_guides) + ggtitle("L5 ET Cluster ID Smart-Seq Patch-Seq"),
nrow = 2
)
```
