---
title: "Seurat figures for off-pipeline data"
author: "SawchukS"
date: "2025-07-16"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      eval = TRUE,
                      out.width = "100%",
                      warning = FALSE,
                      cache = TRUE)

library(metap)
library(feather)
library(Seurat)
library(ggplot2)

MD = projHCT::sheets$MD
cMD = projHCT::sheets$cleanMD

HTRgenesINT = c(
  "HTR1A", "HTR1B", "HTR1D", "HTR1E", "HTR1F", "HTR2A", "HTR2B", "HTR2C", "HTR4", "HTR5A", "HTR6", "HTR7"
)
HTRgenes12 = c("HTR1A", "HTR1B", "HTR1D", "HTR1E", "HTR1F", "HTR2A", "HTR2B", "HTR2C")
HTR1 = c("HTR1A", "HTR1B", "HTR1D", "HTR1E", "HTR1F")
HTR2 = c("HTR2A", "HTR2B", "HTR2C")
HTR0 = c("HTR4", "HTR5A", "HTR6", "HTR7")

legend_guides = c(size = guide_legend(title = "% Exp"), color = guide_colorbar(title = "Avg Exp"))

brain = readRDS("~/proj/proj5HT/data-raw/Seurat/offPipeline-Macaque_SmartSeq.rds")
hMTG = readRDS("~/proj/proj5HT/data-raw/Seurat/offPipeline-Macaque_SmartSeq.rds")
brain[["percent.mt"]] <- PercentageFeatureSet(brain, pattern = "^MT*")

brain = subset(brain.complete, subset = neighbourhoodCorr %in% c("it_types", "l5et_l56np_l6ct_l6b"))
pValbChand = subset(brain.complete, subset = subclass %in% c("Chandelier", "Pvalb"))
```

## Figures
Combined shows nCount_RNA being far from each other
```{r, eval = TRUE}
VlnPlot(brain, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), group.by = "set", ncol = 3)
```

## Violin plots Without Normalizing the data
```{r, fig.height=15, fig.width=12}
VlnPlot(brain, features = HTRgenesINT, pt.size = 0.2, ncol = 4, group.by = "subclass", same.y.lims = TRUE)
VlnPlot(cMTG, features = HTRgenesINT, pt.size = 0.2, ncol = 4, group.by = "subclass_label", same.y.lims = TRUE)
```

```{r, fig.height=4, fig.width=10}
VlnPlot(brain, features = HTR1, pt.size = 0.2, ncol = 5, group.by = "subclass",layer = "counts", same.y.lims = TRUE)
```

```{r, fig.height=4, fig.width=6}
VlnPlot(brain, features = HTR2, pt.size = 0.2, ncol = 3, group.by = "subclass", layer = "counts", same.y.lims = TRUE)
```

```{r, fig.height=4, fig.width=8}
VlnPlot(brain, features = HTR0, pt.size = 0.2, ncol = 4, group.by = "subclass", layer = "counts", same.y.lims = TRUE)
```

## Dotplots
```{r, fig.height=4, fig.width=8, eval =TRUE}
DotPlot(object = brain, features = HTRgenesINT, group.by = "subclass", scale = FALSE) + guides(legend_guides) + ggtitle("Smart-Seq Patch-Seq")


subset(brain, subset = Cortical_area %in% c("TCx", "MCx")) %>% 
DotPlot(object = subset(brain, subset = Cortical_area %in% c("TCx", "MCx")), features = HTRgenesINT, group.by = "subclass", split.by = "Cortical_area", scale = FALSE) + guides(legend_guides)

unique(brain$Cortical_area)

```

```{r, fig.height=8, fig.width=10, eval =FALSE}
DotPlot(object = brain, features = HTR1, group.by = "subclass", scale = FALSE) + guides(legend_guides)
```

```{r, fig.height=8, fig.width=6, eval =FALSE}
DotPlot(object = brain, features = HTR2, group.by = "subclass", scale = FALSE) + guides(legend_guides)
```

```{r, fig.height=8, fig.width=8, eval =FALSE}
DotPlot(object = brain, features = HTR0, group.by = "subclass", scale = FALSE) + guides(legend_guides)
```

## Plot Cluster types 

### L2/3 IT cluster types

```{r}
VlnPlot(object = subset(brain, subset = subclass %in% "L2/3 IT"), features = HTRgenesINT, group.by = "cluster")
```

```{r}

grid.arrange(
DotPlot(object = subset(brain, subset = subclass %in% "L2/3 IT"), features = HTRgenesINT, group.by = "cluster", scale = FALSE) + guides(legend_guides) + ggtitle("L2/3 Cluster ID Smart-Seq Patch-Seq"),
DotPlot(object = subset(cMTG, subset = subclass_label %in% "L2/3 IT"), features = HTRgenesINT, group.by = "cluster", scale = FALSE) + guides(legend_guides) + ggtitle("L2/3 Cluster ID fo 10x-FACs data"),
nrow = 2
)
```

```{r}

brain2 = subset(brain, subset = Cortical_area %in% "TCx")

grid.arrange(
DotPlot(object = subset(brain2, subset = subclass %in% "L5 ET"), features = HTRgenesINT, group.by = "cluster", scale = FALSE) + guides(legend_guides) + ggtitle("L5 ET Cluster ID Smart-Seq Patch-Seq"),
DotPlot(object = subset(brain2, subset = subclass %in% "L2/3 IT"), features = HTRgenesINT, group.by = "cluster", scale = FALSE) + guides(legend_guides) + ggtitle("L2/3 Cluster ID Smart-Seq Patch-Seq"),
#DotPlot(object = subset(cMTG, subset = subclass_label %in% "L5 ET"), features = HTRgenesINT, group.by = "cluster", scale = FALSE) + guides(legend_guides) + ggtitle("L5 ET Cluster ID fo 10x-FACs data"),
#DotPlot(object = subset(cMTG, subset = subclass_label %in% "L2/3 IT"), features = HTRgenesINT, group.by = "cluster", scale = FALSE) + guides(legend_guides) + ggtitle("L2/3 Cluster ID fo 10x-FACs data"),
nrow = 2
)
```

### L5 ET cluster types

```{r}
VlnPlot(object = subset(brain, subset = subclass %in% "L5 ET"), features = HTRgenesINT, group.by = "cluster")
```

```{r}
DotPlot(object = subset(brain, subset = subclass %in% "L5 ET"), features = HTRgenesINT, group.by = "cluster", scale = FALSE) + guides(legend_guides)
```

```{r}

grid.arrange(
DotPlot(object = subset(cMTG, subset = subclass_label %in% "L5 ET"), features = HTRgenesINT, group.by = "cluster", scale = FALSE) + guides(legend_guides) + ggtitle("L5 ET Cluster ID fo 10x-FACs data"),
DotPlot(object = subset(brain, subset = subclass %in% "L5 ET"), features = HTRgenesINT, group.by = "cluster", scale = FALSE) + guides(legend_guides) + ggtitle("L5 ET Cluster ID Smart-Seq Patch-Seq"),
nrow = 2
)
```
