library(projHCT, warn.conflicts = F, quietly = T)
library(nphys, warn.conflicts = F, quietly = T)
library(rhdf5, warn.conflicts = F, quietly = T)
library(ggplot2, warn.conflicts = F, quietly = T)
library(dplyr, warn.conflicts = F, quietly = T)
library(grid, warn.conflicts = F, quietly = T)
library(gridExtra, warn.conflicts = F, quietly = T)
library(Seurat, warn.conflicts = F, quietly = T)
reticulate::use_condaenv(condaenv = "npfx", required = TRUE)
