---
title: "python_filtering"
author: "SawchukS"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(proj5HT)
library(projHCT)
library(magrittr)
knitr::opts_chunk$set(echo = TRUE, cache = TRUE, warnings = FALSE, out.width = "100%")
sh5HT = sheets5HT()
```

```{r}
cells = sh5HT$cells 
print(cells)

```

```{r}
srt = loadHCT(cells[1], tag = "-srt.rds")
# 
# blSweep_name = srt$dfs$spikeTTL$sweep_names[[grep("baseline", names(srt$dfs$spikeTTL$sweep_name))]]
# blpeaks = srt$dfs$spikeTTL$sweep_peaks[[grep("baseline", names(srt$dfs$spikeTTL$sweep_peaks))]]
# blsweep = nphys::extractNWB(srt$md$nwb_file, sweep = blSweep_name, slim = TRUE)


#rhdf5::h5ls(srt$files$nwb, recursive = FALSE)$name

sweep_name = srt$dfs$spikeTTL$sweep_names[[grep("spikeTTL", names(srt$dfs$spikeTTL$sweep_name))]]
TTLpeaks = srt$dfs$spikeTTL$sweep_peaks[[grep("spikeTTL", names(srt$dfs$spikeTTL$sweep_peaks))]]
sweep = nphys::extractNWB(srt$files$nwb, sweep = sweep_name, slim = TRUE)

#srt$smry = returnHCTsmry(srt$cell)

rate = srt$smry$sampling_rate[[grep(sweep_name, srt$smry$acquisition_names)]]

par(mfrow = c(1,1))
plot(sweep, type = "l")
#plot(blsweep, type = "l")
xf = convertIndex(sweep, rate)

fp = as.data.frame(TTLpeaks)
fp = fp[-nrow(fp),]

```


```{r}

ap = 2

isi_seg = sweep[fp[ap,"apOFFi"]:fp[ap+1,"apONi"]]

#plot(ap_seg, type = "l")
par(mfrow = c(1,1))
plot(convertIndex(isi_seg, rate), isi_seg, type = "l")

tst = segmentFilter(isi_seg, rate = rate, show_plot = TRUE, return_segment = TRUE)

par(mfrow = c(1,1))
dvdt_mV(isi_seg, rate)
dvdt_mV(tst, rate)

fltrd = filter_and_plot(isi_seg, rate)

dvdt_mV(isi_seg, rate)

dvdt_mV(as.numeric(fltrd),rate)


```

